model: elasticnet
metric: mae
device: cpu  # cpu|cuda

feature_space:
  lags:
    choices:
      - [1]
      - [1, 2, 3]
      - [1, 3, 6, 12]

  lag_strategy:
    choices: ["value", "ema", "mom"]

  ema_span:
    type: int
    low: 2
    high: 8
    active_if:
      lag_strategy: "ema"

  use_intercorr:
    choices: [true, false]

  intercorr_threshold:
    type: float
    low: 0.85
    high: 0.99
    active_if:
      use_intercorr: true

  intercorr_method:
    choices: ["var", "first"]
    active_if:
      use_intercorr: true

  use_corr_selector:
    choices: [true, false]

  corr_top_k:
    type: int
    low: 25
    high: 300
    step: 25
    active_if:
      use_corr_selector: true

  corr_min_abs:
    type: float
    low: 0.0
    high: 0.3
    active_if:
      use_corr_selector: true

  use_variance_threshold:
    choices: [true, false]

  var_threshold:
    type: float
    low: 1e-8
    high: 1e-5
    log: true
    active_if:
      use_variance_threshold: true

  use_pca:
    choices: [true, false]

  pca_before_lags:
    choices: [true, false]
    active_if:
      use_pca: true

  pca_n_components:
    type: int
    low: 1
    high: 5
    active_if:
      use_pca: true

  use_shock_dummy:
    choices: [false, true]

  shock_sigma:
    type: float
    low: 2.0
    high: 4.0
    active_if:
      use_shock_dummy: true

model_space:
  alpha:
    type: float
    low: 1e-4
    high: 1.0
    log: true
  l1_ratio:
    type: float
    low: 0.0
    high: 1.0
