raw:
  features_dir: data/raw/features
  target_file: data/raw/target/IndustrialProd.xlsx
processed:
  dir: data/processed
  features: data/processed/features.csv
  features_clean: data/processed/cleaned_features.csv
  target: data/processed/target.csv
  target_full: data/processed/target_full.csv
  panel_long: data/processed/ifo_panel.csv
  panel_with_ip: data/processed/panel_with_ip.csv
