seed: 42
metric: mae
split:
  initial_window: 120     # z.B. erste 10 Jahre (bei monatlichen Daten)
  step: 1
  horizon: 1
paths:
  features: data/processed/features.csv
  features_clean: data/processed/cleaned_features.csv
  target: data/processed/target.csv
  reports: reports
  tuned: models/tuned_params
